### PR TITLE
Make the nestedKey only take effect in the serialized object and fix …

### LINKED ISSUE #883: Properly handling the 'nestedKey' option
Let me start by congratulating you guys on this awesome project and by saying I have read #872, #771 and #792 and the docs available [here](https://github.com/pinojs/pino/blob/master/docs/api.md#nestedkey-string).

Personally what I understand from the docs (and what I would expect to happen) is that the serializers will still receive the original object, not the one after the 'nestedKey' transformation (as the base is static, the dynamic part is the passed object and the serializers register only on root level properties, making the serializers register feature pointless when used with 'nestedKey'). But this is my opinion and is subject to interpretation.

However, activating the 'nestedKey' option breaks the standard serialization of errors (because the detection fails) which is a bug (standard options should not break each other).

The problem seems to be that the passed object is transformed [here](https://github.com/pinojs/pino/blob/83d80f63888aa0b68479d460706644c58257131c/lib/tools.js#L47) and afterwards is checked for it's type [here](https://github.com/pinojs/pino/blob/83d80f63888aa0b68479d460706644c58257131c/lib/proto.js#L144) effectively transforming all Errors into plain objects so the detection is never true.

I think it would be a good idea to do the transformation after the check.

If you guys agree I would be happy to make a PR.

### PR DESCRIPTION
**Pull request by mihai1voicescu**
…error detection and serialization (closes #883)

proto.js
* Copy the message property in case the obj is an error and there is a msg specified
* Load the msg as a property of obj if metadata is needed

symbols.js
* Add nestedKeyStrSym to quickly cache the string

tools.js
* Manually build the stringify for performance reasons (not too pretty...)

error.test.js + serializers.test.js
* Add a test for the new nestedKey interaction

### CODE REVIEW

**Comment by mihai1voicescu** [comment]
I finally managed to make the http test run on local... new antivirus :) 

I will fix the coverage ASAP.

File: lib/tools.js [hunk 1]
```diff
@@ -139,11 +137,45 @@ function asJson (obj, msg, num, time) {
...
+    }
+  }
+
+  let msgStr = ''
+  if (msg !== undefined) {
+    value = serializers[messageKey] ? serializers[messageKey](msg) : msg
+    const stringifier = stringifiers[messageKey] || wildcardStringifier
+
+    switch (typeof value) {
+      case 'function':
```
Comment (mihai1voicescu) [inline lib/tools.js:150]: Should I cover all these cases here?

File: lib/tools.js [hunk 2]
```diff
@@ -139,11 +137,45 @@ function asJson (obj, msg, num, time) {
...
+        if (stringifier) value = stringifier(value)
+        msgStr = ',"' + messageKey + '":' + value
+        break
+      case 'string':
+        value = (stringifier || asString)(value)
+        msgStr = ',"' + messageKey + '":' + value
+        break
+      default:
+        value = (stringifier || stringify)(value)
+        msgStr = ',"' + messageKey + '":' + value
```
Comment (mcollina) [inline lib/tools.js:168]: Was this code lifted/copied from somewhere else?

Comment (mihai1voicescu) [reply lib/tools.js:168]: It's the handling of the values from above https://github.com/pinojs/pino/blob/83d80f63888aa0b68479d460706644c58257131c/lib/tools.js#L118

I duplicated it to avoid creating a separate function (for performance reasons).

But maybe all that handling is not needed for only the 'msg' key.

Comment (mihai1voicescu) [reply lib/tools.js:168]: Regrding the benchmarks registered benchmarks on the cloud, they seem to vary by a statistically significant ammount even in the other loggers:
image

But it's very late and I am tired so I might be overlooking something 😄.

I will investigate and get back to you.

Also, do you guys have a better tool other then diff for comparing the performance (maybe something that registers the % gain and the standard deviation of the ran tests)?

And I see the clould machine is an Azure, I guess it's a VM without guaranteed resources so the performance might vary over time (didn't use Azure a lot so I might be mistaken).

Comment (jsumners) [reply lib/tools.js:168]: The benchmarks that are automatically run by the PR process are run in GitHub's Actions platform. At the bottom of each file you will find a summary of the each result that is the average of all the runs for each result type.

Comment (mihai1voicescu) [reply lib/tools.js:168]: I ran the `update-bench-doc` task with both versions on my mac. The results seem to be almost the same (some times one version or the other is faster but not by something significant).

Left side is the old version and the right is the new PR.
image

I think the problem on the clould is the fact that it runs on a VM w/o guaranteed resources. This means performance can vary widly according to the usage of other VMs sharing the same underlying resources.

Do you guys agree? Maybe someone can double check on a phisical machine just to be sure.

Comment (jsumners) [reply lib/tools.js:168]: The VM resources are supposed to be the same across all runs -- https://docs.github.com/en/actions/reference/virtual-environments-for-github-hosted-runners

Anyway, the benchmark action is merely there to provide a quick inspection. True benchmark comparisons need to be run on a dedicated system if the PR benchmarks give an indication that something may be amiss.

Comment (mihai1voicescu) [reply lib/tools.js:168]: So I think that this means the benchmarks are OK. I will resolve this conversation and ask for a re-review.

File: lib/proto.js [hunk 3]
```diff
@@ -148,11 +149,15 @@ function write (_obj, msg, num) {
...
-    }
 
     if (objError) {
+      if (!msg) {
+        // replace the main msg with the message of the error
+        msg = _obj.message
+      } else {
+        // if we do have a msg, we should keep the message found on the error
+        obj.message = _obj.message
+      }
```
Comment (jsumners) [inline lib/proto.js:160]: Why? The current implementation doesn't do this, does it?

File: lib/proto.js [hunk 4]
```diff
@@ -165,6 +170,9 @@ function write (_obj, msg, num) {
   const stream = this[streamSym]
   if (stream[needsMetadataGsym] === true) {
     stream.lastLevel = num
+    if (msg) {
+      obj[this[messageKeySym]] = msg
+    }
```
Comment (jsumners) [inline lib/proto.js:175]: Why is this here?

File: lib/tools.js (hunk 1 above)
Comment (jsumners) [reply lib/tools.js:150]: If this is going to be left in, yes. But I'm really confused as to why it is needed.

**Review by jsumners — DISMISSED** [review]
I think this PR is addressing multiple things at once. If that is the case, please reduce it down to one issue and open subsequent PRs for other issues.

File: lib/tools.js (hunk 1 above)
Comment (mihai1voicescu) [reply lib/tools.js:150]: Well the `msg` key needs to be treated separatly so it can be placed on the root level and not the nested key one.

File: lib/proto.js (hunk 4 above)
Comment (mihai1voicescu) [reply lib/proto.js:175]: If we only pass the obj, if the `nestedKey` option is activated then the obj will have no msg key. If the option is false, then the obj will have the key.

I did this to be as close as possible to the  `nestedKey=false` behavior.

File: lib/proto.js (hunk 3 above)
Comment (mihai1voicescu) [reply lib/proto.js:160]: It's true it does not.

Because it does not it results in loosing the `message` string when a `msg` is present, which, in my oppinion is not OK.

But it's true, maybe this should be a separate issue. Should I make a separate one?

Comment (jsumners) [reply lib/proto.js:160]: Yes, please keep issues scoped to one item. It is very difficult to review PRs that address multiple things. However, see https://github.com/pinojs/pino/pull/882

File: lib/proto.js (hunk 4 above)
Comment (mihai1voicescu) [reply lib/proto.js:175]: The `msg` property is no longer placed on the `obj` in the `asJson` function.

Thing is, the `lastMsg` is also placed here so this is not requeired, but the behaviour will be a little diffrent (although arguably more correct), which I tried to avoid as much as possible, while keeping things performant.

File: lib/proto.js (hunk 3 above)
Comment (mihai1voicescu) [reply lib/proto.js:160]: I created #889. #882 and  #876 do not seem related to this issue.

File: lib/proto.js (hunk 4 above)
Comment (mihai1voicescu) [reply lib/proto.js:175]: After reading #882 I realised the `msg`, as deduced by the algorithm, maybe should not be in the `obj` at all.

This is why you guys put in the `originalMsg`, because you basically wanted both messages. But this is why I used the `nestedKey` (to avoid all collisions).

So maybe the good fix is to not replace the `msg` property in the `obj` and use `nestedKey`.

The [new handling of the `msg` algorithm in the PR](https://github.com/mihai1voicescu/pino/blob/783bbfa20db90a8a617057242851b60c265ee361/lib/tools.js#L146) will place the `msg` key as the last thing in the JSON log w/o interfering with the `obj`.

Comment (mihai1voicescu) [reply lib/proto.js:175]: I will remove the if, and leave the obj without the msg. This is available in lastMsg

**Comment by mihai1voicescu** [comment]
I addressed the issues present in the PR comments.
Note that I solved https://github.com/pinojs/pino/pull/885#discussion_r468515301 by removing the if which causes the `obj` to miss the `msg` property. This is available in `this.lastMsg`. If you are against this I can put it back in.

File: test/basic.test.js [hunk 5]
```diff
@@ -681,3 +681,36 @@ test('correctly log NaN', async (t) => {
...
+  const { msg } = await once(stream, 'data')
+  t.is(msg, null)
+})
+
+test('correctly skip Infinity', async (t) => {
+  const stream = sink()
+  const instance = pino(stream)
+
+  const o = { num: NaN }
+  instance.info(o, 42)
```
Comment (markstos) [inline test/basic.test.js:712]: I think the test name is wrong here-- it appears to simply be a copy/paste of the test name above. Perhaps the intent was "correctly skip Number" ?

File: test/metadata.test.js [hunk 6]
```diff
@@ -40,7 +40,7 @@ test('child loggers works', async ({ ok, same, is }) => {
       is(child, this.lastLogger)
       is(30, this.lastLevel)
       is('a msg', this.lastMsg)
-      same(this.lastObj, { from: 'child', msg: 'a msg' })
+      same(this.lastObj, { from: 'child' })
```
Comment (mcollina) [inline test/metadata.test.js:43]: I have a feeling this might be a semver-major change.

**Review by mcollina — APPROVED** [review]
lgtm, benchmarks are ok

File: test/basic.test.js [hunk 7]
```diff
@@ -681,3 +681,36 @@ test('correctly log NaN', async (t) => {
...
+  const instance = pino(stream)
+
+  const o = { num: NaN }
+  instance.info(o, Infinity)
+
+  const { msg } = await once(stream, 'data')
+  t.is(msg, null)
+})
+
+test('correctly skip Infinity', async (t) => {
```
Comment (mcollina) [inline test/basic.test.js:707]:
```suggestion
test('correctly skip NaN', async (t) => {
```

File: test/basic.test.js (hunk 5 above)
Comment (mcollina) [reply test/basic.test.js:712]: I'm not sure this test is really doing anything actually. @mihai1voicescu can you clarify?

Comment (mihai1voicescu) [reply test/basic.test.js:712]: I forgot to rename the test 😢. Should test that given a number, will print the number as string in the msg.
Basically testing the switch case.

File: test/metadata.test.js (hunk 6 above)
Comment (mihai1voicescu) [reply test/metadata.test.js:43]: I agree, should I update the version in the package.json?

**Comment by jsumners** [comment]
My last review question never got answered. Is this PR solving multiple issues at once?

**Comment by mihai1voicescu** [comment]
@jsumners it is now addressing a single issue (the nested property).
After your comments I split the other stuff in a different issue.

**Comment by mcollina** [comment]
@jsumners are you ok in landing this?

**Comment by jsumners** [comment]
@mcollina sorry, I'm having a really hard time following this and just don't have enough time to devote to it right now. I leave it up to you and @davidmarkclements.

**Comment by mcollina** [comment]
Can you please rebase it? I'm sorry we've let this stale.

**Review by mcollina — APPROVED** [review]
lgtm

**Comment by mihai1voicescu** [comment]
@mcollina looks like one check entitled `CI / 12 macOS-latest (pull_request)` failed but I don't see any logs associated with it.

What should I do?

**Comment by jsumners** [comment]
GitHub Actions is having issues at this time https://www.githubstatus.com/incidents/m16jzl31gnqt
