### PR TITLE
Make sure that the main thread stays alive to process stdout.

### LINKED ISSUE #1074: Calling pino.transport() results in "Error: Not supported"
pino version: '7.0.0-rc.1'

```
$ cat main.js
require("pino").transport({target: "/dev/null"})
$ node main.js
events.js:187
      throw er; // Unhandled 'error' event
      ^

Error: Not supported
    at start (/Users/g.crino/pino-poc/node_modules/thread-stream/lib/worker.js:18:39)
    at Object.<anonymous> (/Users/g.crino/pino-poc/node_modules/thread-stream/lib/worker.js:42:1)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1047:10)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:139:25)
    at MessagePort.emit (events.js:210:5)
    at MessagePort.onmessage (internal/worker/io.js:70:8)
Emitted 'error' event on ThreadStream instance at:
    at /Users/g.crino/pino-poc/node_modules/thread-stream/index.js:155:16
    at processTicksAndRejections (internal/process/task_queues.js:75:11)
```

### PR DESCRIPTION
**Pull request by mcollina**
This is achieved by hooking into beforeExit in on-exit-leak-free.
At that point the event loop is still running so we can catch the
most basic exit scenarios. However this would not work if we use
`process.exit(0)` to exit the main thread.

Fix #1074

### CODE REVIEW

**Comment by mcollina** [comment]
Check out https://github.com/mcollina/on-exit-leak-free/commit/a93961815b32fe663179ee80ed1eb87f5c9509ac if you are curious.

File: test/fixtures/transport-main.js [hunk 1]
```diff
@@ -0,0 +1,9 @@
+'use strict'
+
+const { join } = require('path')
+const pino = require('../..')
+const transport = pino.transport({
+  target: join(__dirname, 'transport-worker.js')
+})
+const logger = pino(transport)
+logger.info('Hello')
```
Comment (kibertoad) [inline test/fixtures/transport-main.js:9]: is it intentional for fixture to export nothing and do something on import?

Comment (mcollina) [reply test/fixtures/transport-main.js:9]: yes, this is called by a child process test.

File: test/transport.test.js [hunk 2]
```diff
@@ -366,3 +368,15 @@ test('pino.transport with target #pino/pretty', async ({ match, teardown }) => {
   const actual = await readFile(destination, 'utf8')
   match(strip(actual), /\[.*\] INFO.*hello/)
 })
+
+test('stdout in worker', async ({ not }) => {
+  let actual = ''
+  const child = execa(process.argv[0], [join(__dirname, 'fixtures', 'transport-main.js')])
```
Comment (kibertoad) [inline test/transport.test.js:374]: this looks more like a script than a fixture, no?

File: test/fixtures/transport-main.js (hunk 1 above)
Comment (kibertoad) [reply test/fixtures/transport-main.js:9]: I'm mostly confused by lack of symmetry here. Some fixtures are supposed to be executed, some imported. Are they still the same kind of things?

File: test/transport.test.js (hunk 2 above)
Comment (mcollina) [reply test/transport.test.js:374]: We place those in `fixtures` - they are almost all the same.

File: test/fixtures/transport-main.js (hunk 1 above)
Comment (mcollina) [reply test/fixtures/transport-main.js:9]: this directory is a place for things that are run from tests. There is no other definition.

**Review by kibertoad — APPROVED** [review]

**Review by davidmarkclements — APPROVED** [review]
looks good to me, do we need to document the process.exit + losing log scenario?

**Comment by jsumners** [comment]
Is this transparent from the library user's perspective? Or have we resurrected https://github.com/pinojs/pino/blob/372a512dc095e50fe9ec3cee82b7ea743619841f/lib/events.js#L4-L8

**Comment by mcollina** [comment]
> Is this transparent from the library user's perspective? Or have we resurrected?:

Nope, it's totally transparent.

**Review by jsumners — APPROVED** [review]

**Review by jsumners — APPROVED** [review]
