### PR TITLE
addLevel bugfixes

### LINKED ISSUE #167: addLevel is not working
__pino 3.1.1__

This fails with: _TypeError: log.foo is not a function_

``` js
const pino = require('pino')
const log = pino()
log.addLevel('foo', 35)
log.foo('bar')
```

The tests does not show this because:
1. Levels added to one instance via the constructor will be added to new instances
2. Adding a level on the constructor works and there exists a test that verifies this. The test creates a new level with the options: `{level:'foo', levelVal: 35}`
3. The test that verifies `addLevel('foo', 35)` is working because it's executed __after__ the test in _(2)_, and because of _(1)_ it uses that function.

If the test in _(3)_ is modified to `addLevel('foo2', 35)`,  the test fails.

Here is some code to show the problem:

``` js
const log = pino({level:'foo', levelVal:35})
const log2 = pino()
log2.foo('should fail, but will work')
```

Three problems exists in the current solution
- `levels` object is shared
- `lscache` object is shared
- `addLevel` does not add a new property

I have a fix for this, which copies `levels` and `lscache` to the instances when new custom levels are added to them. If no custom levels are added the standard values on `Pino.prototype` is used.

Let me know if you want me to submit a PR.

### PR DESCRIPTION
**Pull request by HCanber**
This PR fixes #167

I've split it into three commits.

- a18f09244a28af865bdda1c96f501812b5504f3e Modifies the existing test to show that the current code fails
- dbdd81956087a54a2efbc3f203f16ea7bff1ea10 Adds a new test, that fails, to show that levels created via the constructor exists on other instances as well
- 886be9cce333ec8f230673bc456317cac379d05b Fixes the problems by not sharing levels and lscache between instances.

## Solution
Default `levels` and `_lscache` properties have been added to `Pino.prototype`. These are used when no custom levels have been added. 

##### addLevel()
The first time `addLevel()` is called on a `Pino` instance, new copies of `levels` and `_lscache` are created on the instance and these are then modified to include the new level.

##### Children of parents with custom levels
If a logger instance has custom levels, these are copied over to children as well, when `child()` is called. 

#### NOTE: Parent and children share `levels` and `_lscache`
The objects in `levels` and `_lscache` are shared between the parent and children. This means that if `addLevel` is called on one instance, all others `levels` and `_lscache` properties will contain the new level as well.

I choose to do it like this, in order to not make copies for every child. I think this is a fair tradeoff. 
Custom levels should be added to the first logger instance, before any child logs have been created, and no new levels should be added after that. `API.md` should probably include a comment about this.

### CODE REVIEW

File: pino.js [hunk 1]
```diff
@@ -34,24 +34,40 @@ var levels = {
   debug: 20,
   trace: 10
 }
+Object.freeze(levels)
 
 var nums = Object.keys(levels).reduce(function (o, k) {
   o[levels[k]] = k
   return o
 }, {})
+Object.freeze(nums)
```
Comment (mcollina) [inline pino.js]: `Object.freeze` has a very bad performance reputation. Given that all those globals are done to speed things up, we cannot probably afford this.

**Comment by mcollina** [comment]
Does this have any effect on performance?

File: pino.js (hunk 1 above)
Comment (HCanber) [inline pino.js]: Yes, my thoughts as well. However they can be removed as well, I just kept them to prevent future bugs like this from happening.

**Comment by HCanber** [comment]
I ran basic, child, grandchild & conception a few times and couldn't see any performance changes. Sometimes the tests were slower, sometimes faster.
I haven't looked at the perf test code though. Do they add custom levels?

**Comment by mcollina** [comment]
No, I'm more concerned about the basic/object performance.

**Comment by HCanber** [comment]
The only thing that would affect that is the changes made to `asJson` where `lscache` no longer is a shared value, but exists on the instance, or `Pino.prototype`:

> ````
> var data = this._baseLog + this._lscache[num] + this.time()
> ````
> https://github.com/pinojs/pino/pull/169/files#diff-04e6fb630166e65e0231f8c63a731aa0R254

All other changes affects `addLevel()` and `child()`

File: pino.js [hunk 2]
```diff
@@ -170,7 +184,7 @@ function Pino (opts, stream) {
 }
 
 Pino.prototype = new EventEmitter()
-defineLevelsProperty(Pino.prototype)
+defineLevelsProperty(Pino.prototype, defaultLevelsValues)
```
Comment (jsumners) [inline pino.js]: See my latest update to #168 . This is accomplished with less changes by simply adding the `levels` property at construction instead of on the prototype.

**Comment by jsumners** [comment]
I like the addition of cascading the custom level to the child loggers. If #168 gets accepted as the solution to #167, I'd like to see a PR submitted against the new revision that adds the feature.

File: pino.js (hunk 2 above)
Comment (HCanber) [inline pino.js]: Yes, less code changes, _but_ with your solution you __always__ have to call `defineLevelsProperty` in the `Pino` constructor. For every child. Even if you only use the standard levels. In my solution it's only done when needed, and instead I rely on prototype chaining.

**Comment by HCanber** [comment]
@jsumners This works:

```js
logger.addLevel('foo', 35)
const child = logger.child({})
child.foo('fooo')
```

This does not work:

```js
const child = logger.child({})
logger.addLevel('foo', 35)
child.foo('fooo')  //foo not defined
```

File: pino.js (hunk 2 above)
Comment (davidmarkclements) [inline pino.js]: Tough call, we need numbers to see the effects (prototype lookups also have cost -  but then again v8 is good at amortising)

Comment (jsumners) [inline pino.js]: The rest of @pinojs/core may disagree with me, but I think the constructor is the one place Pino can afford a little time.

**Comment by jsumners** [comment]
@HCanber right. Children are not currently included in `addLevel` my patch in #168 merely addresses the bug present in the current implementation -- state being shared when it shouldn't be.

For the record, whichever solution, mine or yours, the community chooses to use is fine with me. I had a few extra minutes to work on it last night, and I'm responsible for adding the feature in the first place, so I submitted my PR.

File: pino.js (hunk 2 above)
Comment (davidmarkclements) [inline pino.js]: yeah child creation isn't a big deal but I'd rather not slow down the benchmarks either hmmmmm

**Comment by davidmarkclements** [comment]
I agree levels cascading is a good thing - and agree that can also be a separate PR in the case of #168 being accepted. What we need is numbers.

Since we're talking about the same thing, can we move any further discussion to #168 (because it predates #169) - see my comment on #168 regarding benchmark comparisons

One final thing - @HCanber & @jsumners  just to say thanks for putting the effort in here, it's much appreciated - I want to make sure we get the best solution and competing solutions is actually an awesome way to do that. Pino is actually in a very fortunate situation here.

**Comment by mcollina** [comment]
The real thing is to get something that does not slow down child creation at this point. That is done quite a bit within pino-http and others.
