### PR TITLE
Pino browser fixes

### LINKED ISSUE #647: Provide transpiled browser version
Hello,
I'm trying to use pino in a regular next.js project and it fails due to missing polyfills for IE11. Babel does not transpile node_modules by default and the integration is a bit hacky. I recommend to provide a build for the recent most used browsers http://gs.statcounter.com/.

### PR DESCRIPTION
**Pull request by davidmarkclements**
fixes #647 and #649 

NOTE: MERGE and RELEASE https://github.com/pinojs/hapi-pino/pull/79  *FIRST*

In #612 we added symbols to browser pino. 

This is breaking backward compatibility, and rather than add additional bytes for a polyfill to the payload overhead that was already added by including all symbols I think we should remove the symbols from the browser as they were only included for a "very niche use case" in #612.

We can instead update hapi-pino to use Symbol.for since the serializers symbol is a global symbol.

This also includes the smallest possible polyfill for `globalThis` for a standard-compliant cross platform global, see https://github.com/pinojs/pino/issues/649#issuecomment-491525080

### CODE REVIEW

**Comment by jfahrenkrug** [comment]
@davidmarkclements  Not that I'm a reviewer or anything, but what do you think about adding a comment to `polyfillGlobalThis()` that links to https://mathiasbynens.be/notes/globalthis? I think if anyone comes across that code down the line they'd be grateful to have a thorough explanation of the zaniness that is going on ;-)

File: browser.js [hunk 1]
```diff
@@ -162,7 +162,6 @@ pino.levels = {
 }
 
 pino.stdSerializers = stdSerializers
-pino.symbols = require('./lib/symbols')
```
Comment (mcollina) [inline browser.js]: I have a fear that this makes this change semver-major.
I would prefer it not to be.

Comment (davidmarkclements) [reply browser.js]: yep. But I think this is a case of semver purity vs practicality. polyfilling symbols is extra overhead and not fully possible (e.g. typeof symbol). There is only one use case, and it's technically server side - so I think an argument can be made in this case for considering the breaking of browser compat a bug, and removing this to be the solution to that bug. Since  this change along with the hapi-pino change will literally affect no one, as there are no other cases for pino.symbols in the browser.
